config/routes.rb
Rails.application.routes.draw do

  root 'propertys#index'
  
  resources :propertys do
    collection do
      post :confirm
      post :list
      get :list
      get :googlemap
      get :search
      get :popular_list
     end
  end
  
  resources :boards , only:[:index, :show, :edit] do
    collection do
      post :create_notice
      post :create_question
      
      get :write_noticeboards
      get :write_questionboard
    
      post :question_update
      get :notice_update
      post :notice_update
      
      get :question_show

      get :destroy_noticeboards
      get :destroy_questionboard
    end
  end
  
  resources :users, only: [ :new, :create, :show, :edit ,:update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy] do
    collection do
      get :favorite_list
      post :favorite_list
    end
  end
  
  get 'logout' , to: 'sessions#destroy', via: 'delete'
  get 'propertys/search' => 'propertys#search'
  get 'searches/result'
  get 'searches/many_result'
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action:checkSession, only: [:index, :write_noticeboards, :write_questionboard, :create_notice, :create_question, :create_notice, :question_show, :notice_update, :edit,:questionboard,:question_update,:show,:destroy_questionboard]
  before_action:user_have_current, only: [:index, :write_noticeboards, :write_questionboard, :question_show, :edit]
  
  def index
    @noticeboards = Noticeboard.all
    @questionboard = Questionboard.all
  end
  
  def write_noticeboards
    @noticeboards = Noticeboard.new
  end
  
  def write_questionboard
    @questionboard = Questionboard.new
  end
  
  def create_notice
    @noticeboards = Noticeboard.new(notice_params)
    p @noticeboards
    if @noticeboards.save 
      redirect_to boards_path
    else
      logger.debug @noticeboards.errors.inspect
      redirect_to write_noticeboards_boards_path
    end
  end
  
  def create_question
    @questionboard = Questionboard.new(question_params)
    @questionboard.user_id = current_user.id
    p @questionboard
    if @questionboard.save
      redirect_to boards_path
    else
      logger.debug @questionboard.errors.inspect
      
      redirect_to write_questionboard_boards_path
    end
  end
  
  def question_show
    @questionboard = Questionboard.find(params[:id])
  end
  
  def edit 
    @noticeboards = Noticeboard.find(params[:id])
  end
  
  def notice_update
    p params[:noticeboard][:id]
    @noticeboards = Noticeboard.find(params[:noticeboard][:id])
    if @noticeboards.update(notice_params)
      redirect_to boards_path
    else
      redirect_to write_noticeboards_boards_path
    end 
  end
  
  def question_update
    p params[:questionboard][:id]
    @questionboard = Questionboard.find(params[:questionboard][:id])
    p @questionboard
    if @questionboard.update(question_params)
      redirect_to boards_path
    else
      redirect_to boards_path
    end 
  end
  
  
  def questionboard
  end
  
  def show
    @noticeboard = Noticeboard.find(params[:id])
    p @noticeboard
  end
  
  def destroy_noticeboards
    @noticeboard = Noticeboard.find(params[:id])
    p @noticeboard
    @noticeboard.destroy
    redirect_to boards_path
  end
  
  def destroy_questionboard
    @questionboard = Questionboard.find(params[:id])
    @questionboard.destroy
    redirect_to boards_path
  end
  
  private
  
  def notice_params
    params.require(:noticeboard).permit(:name, :title, :content)
  end
  
  def question_params
    params.require(:questionboard).permit(:name, :title, :content, :reply)
  end
  
end

app/helpers/boards_helper.rb
module BoardsHelper

=begin
  def choose_question_new_or_edit 
    if action_name == 'write_questionboard'
      create_question_path
    elsif action_name == 'edit_questionboard'
      property_path
    end
  end
  
  def choose_notice_new_or_edit 
    if action_name == 'write_noticeboards'
      create_notice_path
    elsif action_name == 'edit_noticeboards'
    end
  end
=end

  def choose_notice_new_or_edit 
    if action_name == 'write_noticeboards'
      create_notice_boards_path
    elsif action_name == 'edit'
      notice_update_boards_path
    end
  end

end

app/views/boards/_form.html.erb
<script language='javascript'>
function sub(){
  if($("#title").val() === null || $("#title").val() == ''){  
    alert("タイトルを入力してください。")
    return false;
  }  
  else if($("#content").val() == null || $("#content").val() == ''){  
    alert("コンテンツを入力してください。")
    return false;
  }
};
</script>
<%= form_with(model: @noticeboards, local: true, url: choose_notice_new_or_edit, method: 'post') do |f| %>
<table>
  <tr>
    <td><%= f.label :Name %></td>
    <td><%= f.text_field :name, :value => @user.name , :readonly => true %></td>
  </tr>
  <tr>
    <td><%= f.label :Title %></td> 
    <td><%= f.text_field :title , :value => @noticeboards.title , :id => 'title'%></td>
  </tr>
  <tr>
    <td><%= f.label :Content %></td> 
    <td><%= f.text_area(:content, size: '50x10', :class => 'text_area', :value => @noticeboards.content, :id => 'content' ) %></td>
  </tr>
  <tr>
    <td><%= f.submit 'お知らせ作成', onclick: 'return sub()' %></td>
    <td><%= f.hidden_field :id, :value => @noticeboards.id %></td>
  </tr> 
</table>
<% end %>

app/views/boards/edit.html.erb
<h1>お知らせ修正</h1>
<%= render 'form'%>

app/views/boards/index.html.erb
<hr>
<h1>お知らせ</h1>

<table>
  <tr>
  <% if @user.name == 'admin' %>
    <td><%= link_to 'お知らせ作成', write_noticeboards_boards_path %></td>
  <% end %>
  </tr>
</table>
<br><hr>
<table>
<% if @noticeboards.present? %>
    <tr>
      <th colspan='1'>投稿者</th>
      <th colspan='1'>話題</th>
      <th colspan='1'>作成日</th>
    </tr>
    <br>
  <% @noticeboards.each do |f| %>
    <tr>
      <th><%= f.name %></th>
      <th><%= link_to f.title, board_path(f.id) %></th>
      <th><%= f.created_at %></th>
    <% if @user.name == 'admin' %>
      <th>
        <%= link_to '編集', edit_board_path(f.id), data:{confirm: "お知らせを編集しますか."} %>
      </th>
      <th>
        <%= link_to '削除', destroy_noticeboards_boards_path(id: f.id), data:{confirm: "お知らせを削除しますか."} %>
      </th>
    <% end %>
    </tr>
  <% end %>
<% else %>
  <tr>
    <td colspan='10'><h3>登録されたお知らせがありません。</h3></td>
  </tr>
<% end %>
</table>
<hr>
<h1>お問い合わせ</h1>
<table>
  <tr>
  <% if @user.present? %>
    <td><%= link_to 'お問い合わせ作成', write_questionboard_boards_path %></td>
  <% end %>
  </tr>
</table>
<br><hr>
<table>
<% if @questionboard.present? %>
    <tr>
      <th colspan='1'>投稿者</th>
      <th colspan='1'>話題</th>
      <th colspan='1'>作成日</th>
      <th colspan='1'>reply</th>
    </tr>
    <br>
  <% @questionboard.each do |f| %>
    <tr>
      <th><%= f.name %></th>
      <th><%= link_to f.title, question_show_boards_path(id: f.id) %></th>
      <th><%= f.created_at %></th>
      <% if f.reply == nil %>
        <th bgcolor="#FF0000"> 未対応　</th>
      <% else %>
        <th bgcolor="#00FF00"> Reply済み </th>
      <% end %>
    <% if f.user_id == current_user.id %>
      <%# <th><%= link_to '編集', question_update_boards_path(id: f.id), data:{confirm: "お問い合わせを編集しますか."} </th>%>
      <th>
        <%= link_to '削除', destroy_questionboard_boards_path(id: f.id), data:{confirm: "お問い合わせを削除しますか."} %>
      </th>
    <% end %>
    </tr>
  <% end %>
<% else %>
  <tr>
    <td colspan='10'><h3>登録されたお問い合わせがありません。</h3></td>
  </tr>
<% end %>
</table>

app/views/boards/question_show.html.erb
<hr>
<table>
  <tr>
    <td>Name</td>
  </tr>
  <tr>
    <td><%= @questionboard.name %></td>
  </tr>
  <tr>
    <td>Title</td>
  </tr>  
  <tr>
    <td><%= @questionboard.title %></td>
  </tr>
  <tr>
    <td colspan='2'>Content</td>
  </tr>
  <tr>    
    <td colspan='2'><%= @questionboard.content %></td>
  </tr>
  <tr>
    <td colspan='2'>reply</td>
  </tr>
  <% if @user.name == 'admin' %>
    <%= form_with(model: @questionboard, local: true, url: question_update_boards_path, method: 'post') do |f| %>
      <% if @questionboard.reply == nil %>
      <tr>
        <td colspan='2'><%= f.text_field :reply %></td>
      </tr>
      <% else %>
      <tr>  
        <td><%= f.text_field :reply, value: @questionboard.reply %></td>
      </tr>
      <% end %>
      <td><%= f.hidden_field :name, value: @questionboard.name %></td>    
      <td><%= f.hidden_field :title, value: @questionboard.title %></td>
      <td><%= f.hidden_field :content, value: @questionboard.content %></td>
      <td><%= f.hidden_field :id, value: @questionboard.id %></td>
      <tr>
        <td><%= f.submit 'reply登録'%></td>
      </tr>
    <% end %>
  <!-- 로그인한 유저가 운영자가아닐경우  -->
  <% elsif  @questionboard.reply != nil %>
    <td><%= @questionboard.reply %></td>
  <% else %>
    <td>登録されたreplyがありません。少々お待ちください。</td>
  <% end %>    
</table>

app/views/boards/show.html.erb
<hr>
<table>
  <tr>
    <td>Name</td> 
  </tr>
  </tr>
    <td><%= @noticeboard.name %></td>
  </tr>
  <tr>
    <td>Title</td> 
  </tr>  
  <tr>
    <td><%= @noticeboard.title %></td>
  </tr>
  <tr>
    <td>Content</td>
  </tr>
  <tr>
    <td><%= @noticeboard.content %></td>
  </tr>
</table>

app/views/boards/write_noticeboards.html.erb
<h1>お知らせ作成</h1>
<%= render 'form'%>

app/views/boards/write_questionboard.html.erb
<script language='javascript'>
function sub(){
  if($("#title").val() === null || $("#title").val() == ''){  
    alert("タイトルを入力してください。")
    return false;
  }  
  else if($("#content").val() == null || $("#content").val() == ''){  
    alert("コンテンツを入力してください。")
    return false;
  }
};
</script>
<% if @questionboard.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@questionboard.errors.count, "error") %> prohibited this @questionboard from being saved:</h2>
    <ul>
    <% @questionboard.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<h1>お問い合わせ作成</h1>
<%= form_with(model: @questionboard, local: true, url: create_question_boards_path, method: 'post') do |f| %>
<table>
  <tr>
    <td><%= f.label :Name %></td> 
    <td><%= f.text_field :name, :value => @user.name , :readonly => true %></td>
  </tr>
  <tr>
    <td><%= f.label :Title %></td> 
    <td><%= f.text_field :title, :id => 'title' %></td>
  </tr>
  <tr>
    <td><%= f.label :Content %></td> 
    <td><%= f.text_area(:content, size: '50x10', :class => 'text_area', :id => 'content' ) %></td>
  </tr> 
  <tr>
    <td><%= f.submit 'お問い合わせ作成', onclick: 'return sub()' %></td>
  </tr>  
</table>
<% end %>