config/routes.rb
Rails.application.routes.draw do

  root 'propertys#index'
  
  resources :propertys do
    collection do
      post :confirm
      post :list
      get :list
      get :googlemap
      get :search
      get :popular_list
     end
  end
  
  resources :boards , only:[:index, :show, :edit] do
    collection do
      post :create_notice
      post :create_question
      
      get :write_noticeboards
      get :write_questionboard
    
      post :question_update
      get :notice_update
      post :notice_update
      
      get :question_show

      get :destroy_noticeboards
      get :destroy_questionboard
    end
  end
  
  resources :users, only: [ :new, :create, :show, :edit ,:update]
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy] do
    collection do
      get :favorite_list
      post :favorite_list
    end
  end
  
  get 'logout' , to: 'sessions#destroy', via: 'delete'
  get 'propertys/search' => 'propertys#search'
  get 'searches/result'
  get 'searches/many_result'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action:checkSession, only: [:result, :many_result]
  
  def index
  end
  
  def result
    @searches = eval(params[:bulletin]).where('created_at >= :years_ago', :years_ago => Time.now - 1.years).where("name like ?", "%#{params[:search_text]}%")
  end
  
  def many_result
    @result = Property.ransack(params[:q])
    p @result
    @searches = @result.result
    p @searches
   #@searches = eval(params[:bulletin]).where("name like ?", "%#{params[:search_text]}%")
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search_form.html.erb
<table>
  <tr>
    <%= form_tag(searches_result_path, method: "get") do %> <%# method를 get방식으로 받아내며, parameter가 /searches/result로 넘어갈 예정. %>
      <td><%= label_tag(:div, "物件名 ") %></td>
      <td><%= text_field_tag(:search_text) %></td>
      <td><%= submit_tag("検索") %></td><%# 검색 하고자 하는 단어를 입력받음, 이 떄 name은 [검색 단어] %>
      <%= hidden_field_tag(:bulletin, "#{post}") %><%# 모델 이름을 자동으로 받아냄 (name은 [bulletin], value 값에는 [모델 이름]이 들어감) %>
    <% end %>
  </tr>
</table>

app/views/searches/_select_search_form.html.erb
<%= search_form_for(@q, url:searches_many_result_path) do |f| %>
<table>
  <tr>
    <td></td>
    <td><%= f.label :rent, '家賃'%></td>
    <td><%= f.label :subsidy, '敷金'%></td>
    <td><%= f.label :reward, '礼金' %></td>
    <td><%= f.label :reward, '広さ(㎡)' %></td>
    <td><%= f.label :extent, '間取り'%></td>
  </tr>    
  <tr>
    <td></td>
    <td><%= f.select :rent_gteq, [['3万以上~', '3'], ['4万以上~', '4'],['5万以上~', '5'],['6万以上~', '6']], :include_blank => '指定なし' %></td>
    <td><%= f.select :subsidy_eq, [['なし', 'なし'], ['1ヵ月', '1ヵ月'],['2ヵ月', '2ヵ月']], :include_blank => '指定なし' %></td>
    <td><%= f.select :reward_eq, [['なし', 'なし'], ['1ヵ月', '1ヵ月'],['2ヵ月', '2ヵ月']], :include_blank => '指定なし' %></td>
    <td><%= f.select :area_gteq, [['20(㎡)以上~', '20'], ['25(㎡)以上~', '25'],['30(㎡)以上~', '30'],['35(㎡)以上~', '35'],['40(㎡)以上~', '40'],['45(㎡)以上~', '45']], :include_blank => '指定なし' %></td>
    <td><%= f.select :extent_eq, [['1R','1R'], ['1K','1K'],['1DK','1DK'],['1LDK','1LDK'],['2K','2K'],['2LDK','2LDK'],['3K','3K'],['3DK','3DK'],['3LDK','3LDK'],['4K','4K']], :include_blank => '指定なし' %></td>
    <td><%= f.submit '検索' %></td>
  </tr>
</table>
<% end %>

app/views/searches/many_result.html.erb
<h1>条件検索結果は下記になります。</h1>
<table>
<% if @searches.present? %>
    <tr>
      <th colspan='1'>投稿者</th>
      <th colspan='4'>物件写真</th>
      <th colspan='3'>物件名</th>
      <th colspan='3'>家賃</th>
      <th colspan='3'>敷金</th>
      <th colspan='3'>礼金</th>
      <th colspan='3'>広さ(㎡)</th>
      <th colspan='3'>間取り</th>
      <th colspan='3'>クリック数</th>
    </tr>
  <% @searches.each do |f| %>
    <tr>
      <th colspan='1'><%= f.user.name %></th>
      <th colspan='4'>
        <%= link_to property_path(f.id) do %>
          <%= image_tag(f.image[0].url, size:"60x60") %>
        <% end %>
      </th>
      <th colspan='3'><%= link_to f.name, property_path(f.id) %></th>
      <th colspan='3'><%= f.rent %>万</th>
      <th colspan='3'><%= f.subsidy %></th>
      <th colspan='3'><%= f.reward %></th>
      <th colspan='3'><%= f.area %></th>
      <th colspan='3'><%= f.extent %></th>
      <th colspan='3'><%= f.impressionist_count %></th>
    <% unless @user.present? %>
      <% if f.user_id == current_user.id %>
        <th>
          <%= link_to '編集', edit_property_path(f.id), data:{confirm: "物件情報を編集しますか."} %>
        </th>
        <th>
          <%= link_to '削除', property_path(f.id), method: :delete, data:{confirm: "物件を削除しますか."} %>
        </th>
      <% end %>
    <% end %>
    </tr>
  <% end %>
<% else %>
  <tr>
    <td colspan='10'><h3>登録された物件がありません。</h3></td>
  </tr>
<% end %>
</table>

app/views/searches/result.html.erb
<h1>検索結果は下記になります。</h1>
<div>
  <table>
  <% if @searches.present? %>      
      <tr>
        <th>投稿者</th>
        <th>物件写真</th>
        <th>物件名</th>
        <th>家賃</th>
        <th>敷金</th>
        <th>礼金</th>
        <th>広さ(㎡)</th>
        <th>間取り</th>
      </tr>
    <% @searches.each do |x| %>
      <tr>
        <th><%= x.user.name %></th>
        <th>
          <%= link_to property_path(x.id) do %>
            <%= image_tag(x.image[0].url, size:"60x60") %>
          <% end %>
        </th>
        <th><%= link_to x.name, property_path(x.id) %></th>
        <th><%= x.rent %>万</th>
        <th><%= x.subsidy %></th>
        <th><%= x.reward %></th>
        <th><%= x.area %></th>
        <th><%= x.extent %></th>
    <% if x.user_id == current_user.id %>
      <th>
        <%= link_to '編集', edit_property_path(x.id), data:{confirm: "物件情報を編集しますか."} %>
      </th>
      <th>
        <%= link_to '削除', property_path(x.id), method: :delete, data:{confirm: "物件を削除しますか."} %>
      </th>
    <% end %>
    </tr>
  <% end %>
<% else %>
  <tr>
    <td colspan='10'><h3>登録された物件がありません。</h3></td>
  </tr>
<% end %>
</table>
</div>